### ISSUE TITLE
Some bedrock blocks have incorrect Property in 1.20

### ISSUE THREAD

**Issue by CoolLoong** [GeyserMC/mappings-generator#57]
```
"minecraft:observer[facing=north,powered=true]": {
    "bedrock_identifier": "minecraft:observer",
    "block_hardness": 3.0,
    "collision_index": 1,
    "can_break_with_hand": false,
    "bedrock_states": {
      "facing_direction": 2,
      "powered_bit": true
    }
  }
```

`facing_direction` should be `minecraft:facing_direction`

the `minecraft:facing_direction` property info
`minecraft:facing_direction`=down,east,north,south,up,west

**Comment by Konicai** [comment]
I'll look into this, but Geyser uses these mappings, and if the block states were incorrect, Geyser would fail to start.

Bedrock has this fun thing where it slowly updates different blocks and items to newer formats over a long period of time

**Comment by onebeastchris** [comment]
I'm pretty sure Geyser accounts for these properties right now on its own, but mappings aren't :p
Since the mappings tend to target the lowest supported Geyser version

found it:
https://github.com/GeyserMC/Geyser/commit/340be2d8a4221c4897d5380409967fa1aa87ab29

**Comment by Konicai** [comment]
Nice.

Yeah, these mappings are currently for 1.20, not 1.20.10
