### ISSUE TITLE
Keep providing the old format of `blocks.json`

### ISSUE THREAD

**Issue by smartcmd** [GeyserMC/mappings-generator#73]
The old format of blocks mappings (blocks.json) is easier to use and is platform agnostic. 
Through the old one is much bigger than the new one (blocks.nbt), I still think it should be kept so that other projects can use it.

![image](https://github.com/GeyserMC/mappings-generator/assets/60499296/e7cee292-7ebf-478b-9f6c-f30aebfe12f1)

**Comment by Camotoy** [comment]
Hello! I'm glad that you found a use with our mappings.

At the end of the day, our mappings were never truly designed as a standard for usage in other projects. We certainly didn't track other projects using them. In that respect, feel free to fork mappings-generator and start from the previous blocks.json commit for your own use-case. You can hop onto our Geyser Discord if you need some help. 
Alternatively, we moved a lot of blocks.json to the GenerateBlocksClass here, if you want to use that exactly, but that's very strictly built for Java Edition blocks and designed for use within Geyser itself. You'd probably still want to fork for your specific use case, even then.
